# Config file for automatic testing at travis-ci.org

language: python
matrix:
  fast_finish: true

  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "pypy"
      env: TOXENV=pypy
    - python: "pypy3"
      env: TOXENV=pypy3
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true

    # Prevent breakage by a new releases
    - python: "3.6-dev"
      env: TOXENV=py36
    - python: "3.7-dev"
      env: TOXENV=py37

    # Meta
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=manifest

  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"

install: pip install tox

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cfp2000
  password:
    secure: OqOIyXUyAlSV47Pq5m4UTQMCyV3auqzw3cTqfK6Im6RrcTJjASwZOzvgmZEt5Od83EXRY4szyte4NNWwpGW8orNtQoryB2Xbxad0BngX+wyWgclnaGwALdqIfw5ISlBwjASXoMsKt2sy0CQHSYn+LCBRtE7xBUnTvY3j/vHx/dj5ODHkjiFmdx+zF6N46Fq88OZBExca3jzT6POeuwom18oK1iwEIH1aB7W4PtCLUNbcftS5wNp/UUoy81ASHoIcKVapQXK25Ub2uOoqwHKNxH16JpxWhWbx49uUNCkp1XZYJtT+1ct2zXh3jzMWV+mkCPV6j5Qafc2QMTfTxOOTmOSh5cAQ6wHdTOcOLbJW60wCJrafM6Dwr4dgBnBbV6Y4goQ4M66Um7a7GP/55fX2Yh1+PQ/5TkqQqn6caBFP9UM9O5OIYwHwMs70b2Dv2SUsQejixH/mSwuTFbeKphj6ztF9qAaO2xbWsGQsrPTmquKN+HmCDiG7lFrxHgtmrARko2oFfWsMSFpopDIvPvmrRv8jShGrpOozbpwkfW3AhPS9Pwpe6OVmaKs39j9yGu1ApLO1upQFTVdQQ+3UsJgvuhMmxgc9Djr/H/zBnx7NBzbOyvixFRlOI8kQpdD1rT3/cw0O8mrZ85sFRpSPo+srS8vFGfNotLTNYRkwNAuoq9A=
  on:
    tags: true
    repo: cfp2000/understreck
    python: 3.6
